#출처: https://school.programmers.co.kr/learn/courses/30/lessons/284531
#문제: 코딩테스트 연습 > GROUP BY >노선별 평균 역 사이 거리 조회하기

SELECT ROUTE, 
CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1),'km') AS TOTAL_DISTANCE, 
CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC;
